apiVersion: v1
kind: Secret
metadata:
  name: jenkins-secrets
  namespace: {{ .Values.jenkins.namespace }}
type: Opaque
stringData:
  GITHUB_TOKEN: ""
  DOCKER_USERNAME: "admin"
  DOCKER_PASSWORD: "admin"
  ARGOCD_TOKEN: ""
