apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - namespace.yaml

helmCharts:
  - name: app1
    repo: oci://localhost:5000/helm-charts
    version: 1.0.0
    releaseName: app1-node
    namespace: dev
    valuesFile: app1-values.yaml
  
  - name: app2
    repo: oci://localhost:5000/helm-charts
    version: 1.0.0
    releaseName: app2-python
    namespace: dev
    valuesFile: app2-values.yaml

commonLabels:
  environment: dev
  managed-by: kustomize

commonAnnotations:
  team: platform
  tier: dev
